#file 2

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: YWRtaW4=
  # needs to be in base64. command on powershell: [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("admin"))
  mongo-password: cGFzc3dvcmQ=
  # command on powershell: [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("password")) 